# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dc82ec6cdd0eafab959784591c862571989b971c5303e64f3228c39adea81d6028e0e9108a4decb9c5065e3fed671079c5c95f2b2e94dc4046227370d59407c

test:
  secret_key_base: f0c70076da16b04e08cf635ae77eb77def6b9bb7c12b43c9851e413420d0802bc626628e79de9715572055a97031bf15ff805b7dc515e4aa2d56d82b79273d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
